### ISSUE TITLE
Running barebones example gives TypeError: Failed to construct URL

### ISSUE THREAD

**Issue by mmoerman** [SilentRhetoric/solid-algo-wallets-example#4]
When cloning the example and doing "npm i" then "npm start" and connecting to the running app, I get the following console error in the browser. This is using Edge or Chrome.

urlTokenBaseHTTPClient.ts:60  Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at new _URLTokenBaseHTTPClient (urlTokenBaseHTTPClient.ts:60:27)
    at new _HTTPClient (client.ts:98:17)
    at new ServiceClient (serviceClient.ts:67:16)
    at new AlgodClient (algod.ts:90:5)
    at Object.fn (dev.jsx:894:12)
    at runComputation (dev.js:788:22)
    at updateComputation (dev.js:766:3)
    at createMemo (dev.js:268:10)
    at UseNetwork (dev.jsx:889:23)
    at dev.js:185:11
_URLTokenBaseHTTPClient @ urlTokenBaseHTTPClient.ts:60
_HTTPClient @ client.ts:98
ServiceClient @ serviceClient.ts:67
AlgodClient @ algod.ts:90
(anonymous) @ dev.jsx:894
runComputation @ dev.js:788
updateComputation @ dev.js:766
createMemo @ dev.js:268
UseNetwork @ dev.jsx:889
(anonymous) @ dev.js:185
runUpdates @ dev.js:900
createRoot @ dev.js:193
(anonymous) @ dev.jsx:989

Note that this error is preceded by the following warning but I do not think this is related.

browser-external:buffer:9  Module "buffer" has been externalized for browser compatibility. Cannot access "buffer.Buffer" in client code. See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
get @ browser-external:buffer:9
(anonymous) @ bn.js:53
node_modules/bn.js/lib/bn.js @ bn.js:3427
__require2 @ chunk-W7S2ME4R.js?v=76bfdf1d:18
node_modules/@walletconnect/utils/dist/esm/encoding.js @ encoding.ts:1
__init @ chunk-W7S2ME4R.js?v=76bfdf1d:15
node_modules/@walletconnect/utils/dist/esm/index.js @ index.ts:4
__init @ chunk-W7S2ME4R.js?v=76bfdf1d:15
node_modules/@walletconnect/core/dist/esm/index.js @ index.ts:28
__init @ chunk-W7S2ME4R.js?v=76bfdf1d:15
node_modules/@walletconnect/client/dist/esm/index.js @ index.ts:1
__init @ chunk-W7S2ME4R.js?v=76bfdf1d:15
node_modules/@perawallet/connect/dist/index-87ee6d1d.js @ index-87ee6d1d.js:1
__require2 @ chunk-W7S2ME4R.js?v=76bfdf1d:18
node_modules/@perawallet/connect/dist/index.js @ index.js:1
__require2 @ chunk-W7S2ME4R.js?v=76bfdf1d:18
(anonymous) @ index.js:1

**Comment by SilentRhetoric** [comment]
Have you set up your .env file using the template?

The buffer message is just a warning and should not cause any problems running the app.

**Comment by mmoerman** [comment]
No I was following the instructions from the website (https://developer.algorand.org/tutorials/build-a-solidjs-web-app-with-wallet-integration/), and not the README in git. My bad its working now.

Thanks for the quick response

**Comment by SilentRhetoric** [comment]
Thanks for reading my article, trying the example app, and reporting the missing step in the instructions!  I have now edited the article to add the step about configuring the .env file so that no one else gets stuck there.  Shout at me if you have any questions.

As an aside, please note that this repo will not be developed further.  Instead, I am working with TxnLab to add a SolidJS module to V3 of the excellent use-wallet library that is currently in Beta here: [https://github.com/TxnLab/use-wallet/tree/v3](https://github.com/TxnLab/use-wallet/tree/v3)

**Comment by mmoerman** [comment]
No worries Brian, this repo was very helpful in my exploration of integration with wallets. I've now done the integration a bit differently but it was really helpful. I'll checkout the new library when I get a bit further down the road with my current project.

Have a great day,
Michael.
________________________________
